#!/usr/bin/env sh

limelight -m config width            3
limelight -m config radius           9
limelight -m config placement        interior
#limelight -m config active_color     0xff775759
limelight -m config active_color     0xff446BC0
limelight -m config normal_color     0xff555555

echo "limelight configuration loaded"
